- backend/src/auth/intra42.controller.spec.ts
- backend/src/users/memdb.mock.ts
- backend/src/users/users.resolver.spec.ts
- backend/src/users/users.service.spec.ts
Per #94 
- Now we can inject other service in providers when creating testing module
- Await all test expect resolves/rejects to avoid test finish before expect finish
- Switch to Datasource instead of Connection
Also we should add run test with CI
> Update backend test

- Makefile
- backend/src/auth/controller/intra42.controller.ts
- backend/src/users/users.service.ts
fixed a bug in the login redirect
Could not properly login with empty database.
Just got an error.
> added makefile rule for removing volume - 

- backend/src/auth/strategy/intra42.strategy.ts
titus the quite tilted temperer rules the titles like the tide
tldr get the current title as your title
> titus rules the titles

- backend/src/prc/prc.gateway.ts
- frontend/src/App.vue
- frontend/src/components/ChatChatComponent.vue
- frontend/src/components/ModalComponent.vue
- frontend/src/plugin/socket.ts
- frontend/src/store/error.ts
Setup store on the frontend which stores all errors and displays a modal with the error message for each. I also updated the prc websocket gateway to send the errors to the client.
> 79 frontend error handling

- frontend/src/components/ChannelsChatComponent.vue
- frontend/src/components/ChatChannelComponent.vue
- frontend/src/components/ChatClientComponent.vue
- frontend/src/components/FriendsPeopleChatComponent.vue
- frontend/src/components/RequestChatComponent.vue
- frontend/src/components/RequestsChatComponent.vue
Simple Request Component created
> 70 chat chat request component

- backend/src/auth/strategy/jwt.strategy.ts
- backend/src/users/decorator/current-jwt-payload.decorator.ts
- Add decorator to get Jwt payload
- Add jwt payload interface
- as parameter `@CurrentJwtPayload() jwtPayload: JwtPayload`
> add decorator to get jwt payload from http/graphql request

- backend/src/users/decorator/current-user.decorator.ts
- backend/src/users/decorator/pipe-user.pipe.spec.ts
- backend/src/users/decorator/user-pipe.service.ts
- backend/src/users/users.module.ts
Add decorator to get current user from database with id from jwt payload
> add decorator to get current user

- frontend/src/service/UserService.ts
> a bit of trolling is to be expected

- frontend/src/components/chat/options/ParentOptionsComponent.vue
- frontend/src/views/ChatView.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/ProfileView.vue
added the design for the chat options
made the client object accessible 
fixed vertical spacing issue for component being only half height
> 72 chat chat options component

- Makefile
- backend/docs/classes/prc_channel_channel_service.ChannelService.md
- backend/docs/classes/prc_message_message.Message.md
- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/docs/modules.md
- backend/docs/modules/prc_message_message.md
- backend/src/prc/channel/channel.service.ts
- backend/src/prc/message/message.ts
- backend/src/prc/prc.gateway.ts
- frontend/src/App.vue
- frontend/src/components/chat/chat/ParentChatComponent.vue
- frontend/src/store/message.ts
Messages are currently also stored on 'Channels' and probably should also be moved to database
> Persistant messaging 

- Makefile
- backend/src/prc/channel/channel-user/channel-user.resolver.spec.ts
- backend/src/prc/channel/channel-user/channel-user.resolver.ts
- backend/src/prc/channel/channel-user/channel-user.service.spec.ts
- backend/src/prc/channel/channel.service.spec.ts
- backend/src/prc/channel/channel.service.ts
Create Tests:
Join Tests:
> - [x] Set User as owner
> - [x] Not Join on bad password
> - [x] Not owner/admin on join
> - [x] Not Join if already in Channel
Password Tests:
> Add Test for Join and Password

- backend/docs/classes/auth_controller_intra42_controller.Intra42Controller.md
- backend/src/auth/controller/intra42.controller.ts
- backend/src/auth/guard/intra42.guard.ts
Fixed backdoor bad request thingy by giving coalitions a default value
> set default coalition for backdoor

- backend/docs/classes/prc_message_message.Message.md
- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/src/prc/channel/channel.service.ts
- backend/src/prc/message/message.ts
- backend/src/prc/prc.gateway.ts
- backend/src/schema.gql
- frontend/src/components/chat/chat/ParentChatComponent.vue
- frontend/src/store/message.ts
Streamline message to have name in both from and to and mitigate problem with double sent messages
> Fix double messages

- frontend/src/router/index.ts
- frontend/src/views/QueueView.vue
created new view with css animations for the queue and added the page to the router, while we don't have a game-page
> adding queue view

- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/src/prc/prc.gateway.ts
- frontend/src/components/chat/channels/ModalChannelComponent.vue
- frontend/src/components/chat/channels/ParentChannelsComponent.vue
- frontend/src/store/message.ts
- frontend/src/views/ChatView.vue
Now if you join a channel, that channel gets added to your list of channels
> Channel List gets updated on join

- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/src/prc/prc.gateway.ts
- frontend/src/components/chat/channels/ModalChannelComponent.vue
- frontend/src/components/chat/channels/ParentChannelsComponent.vue
- frontend/src/store/message.ts
- frontend/src/views/ChatView.vue
* Now if you join a channel, that channel gets added to your list of channels
* Update Documentation
* Fix style
Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
> Channel List gets updated on join (#292)

- frontend/src/components/chat/options/ParentOptionsComponent.vue
- frontend/src/components/chat/peoples/ChildPeopleComponent.vue
- frontend/src/components/chat/peoples/ParentPeoplesComponent.vue
- frontend/src/views/ChatView.vue
> added emit for starting a chat with a user by clicking on the

- frontend/src/components/chat/peoples/ChildPeopleComponent.vue
- frontend/src/components/profile/profile/ProfileComponent.vue
should attatch to the status being updatedm but makes it easier to identify
> hopefully fixes issue, merge game first

- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/src/prc/prc.gateway.ts
- frontend/src/App.vue
Now as soon as you log in with the same user in a second window/tab, the first one will be logged out.
> Add logout if new client connects

- backend/docs/classes/users_entities_user_entity.User.md
- backend/docs/classes/users_users_resolver.UsersResolver.md
- backend/src/schema.gql
- backend/src/users/entities/user.entity.ts
- backend/src/users/users.resolver.spec.ts
- backend/src/users/users.resolver.ts
Only return actual status in graphQL if friend
> only show status if friends

- backend/docs/classes/prc_channel_channel_resolver.ChannelResolver.md
- backend/docs/classes/prc_channel_channel_user_channel_user_resolver.ChannelUserResolver.md
- backend/docs/classes/prc_channel_channel_user_channel_user_service.ChannelUserService.md
- backend/src/prc/channel/channel-user/channel-user.resolver.ts
- backend/src/prc/channel/channel-user/channel-user.service.ts
- backend/src/prc/channel/channel.resolver.ts
- backend/src/schema.gql
- channel query already only expose those that you're in or public
- remove unused channel query
- channel users query return only those of channel that you're in or public
> only expose channel users of channel you're in or public

- backend/docs/classes/prc_channel_channel_user_channel_user_resolver.ChannelUserResolver.md
- backend/docs/classes/prc_channel_channel_user_channel_user_service.ChannelUserService.md
- backend/docs/classes/prc_channel_channel_user_entities_channel_user_entity.ChannelUser.md
- backend/src/prc/channel/channel-user/channel-user.resolver.ts
- backend/src/prc/channel/channel-user/channel-user.service.ts
- backend/src/prc/channel/channel-user/entities/channel-user.entity.ts
- backend/src/schema.gql
Query all channel users given channel name
> query channel users in channel

- Makefile
- frontend/src/components/chat/channels/ModalChannelComponent.vue
Fixing empty text field input.
Adding # in front of the users input, if the user did not use the hashtag as a name of channel which it wishes to join/create #332 
Removing double quotes from Makefile for windows users.
> add in front of the channel if the user hasnt entered it

- backend/src/game/game.resolver.ts
- backend/src/game/game.service.ts
- backend/src/schema.gql
- frontend/src/components/chat/peoples/ChildPeopleComponent.vue
- frontend/src/components/globalUse/UserPlayedGameComponent.vue
- frontend/src/components/profile/history/ParentHistoryComponent.vue
- frontend/src/components/stream/ChildStreamComponent.vue
- frontend/src/service/GameService.ts
- frontend/src/views/StreamView.vue
The Stream Page displays all running matches, while your user page displays your own played games
> Add matches to stream page and profile page

- backend/docs/classes/prc_channel_channel_resolver.ChannelResolver.md
- backend/docs/classes/prc_channel_channel_user_channel_user_resolver.ChannelUserResolver.md
- backend/docs/classes/tools_ExceptionFilter.CustomPrcExceptionFilter.md
- backend/src/prc/channel/channel-user/channel-user.resolver.spec.ts
- backend/src/prc/channel/channel-user/channel-user.resolver.ts
- backend/src/prc/channel/channel.resolver.ts
- backend/src/tools/ExceptionFilter.ts
- frontend/src/service/ChannelUserService.ts
Although we throw WsException, which is not ideal but frontend should capture and display correct error message. Only problem is Nestjs still logs this exception, this PR is to suppress it.
> suppress wsexcpetion in resolver

- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/src/prc/prc.gateway.ts
- if a user is muted/blocked from the channel, that user can't write in the channel(need a refresh of the page).
- if you block a user individually it can't write you private messages, however, it can still write in the channel, you and that specific user are in.
> 347 implement mute and block functionality

- Makefile
- backend/docs/classes/game_game_gateway.GameGateway.md
- backend/docs/classes/game_game_service.GameService.md
- backend/docs/classes/users_users_service.UsersService.md
- backend/src/game/game.gateway.ts
- backend/src/game/game.service.ts
- backend/src/users/users.service.ts
Removed the user once his socket disconnects.
> Remove user from queue when disconnected

- frontend/src/components/game/PongComponent.vue
- frontend/src/components/game/QueueComponent.vue
- frontend/src/components/game/ball.ts
maybe fix
henne take a look on this
> 317 unregister keyhooks after game

- frontend/src/components/profile/profile/ProfileComponent.vue
Co-authored-by: Eduard-Hosu <ehosu@student.42wolfsburg.de>
> adding dynamic rank near users picture on profile page

- backend/docs/classes/prc_channel_channel_user_channel_user_resolver.ChannelUserResolver.md
- backend/docs/classes/prc_channel_channel_user_channel_user_service.ChannelUserService.md
- backend/src/prc/channel/channel-user/channel-user.resolver.spec.ts
- backend/src/prc/channel/channel-user/channel-user.resolver.ts
- backend/src/prc/channel/channel-user/channel-user.service.spec.ts
- backend/src/prc/channel/channel-user/channel-user.service.ts
- backend/src/prc/channel/channel.service.ts
there is still no way to force the user to refresh so they are still in the chat "view" but they cant do anything
also they see messages that were sent when they rejoin
> 348 implement ban functionality 2

- frontend/src/components/game/EndScreenComponent.vue
- frontend/src/components/game/QueueComponent.vue
Don't even try to ask the backend for info, if the gameId is 0. Also add more error reporting to more functions in the game
> Don't query game if id is 0

- frontend/src/components/chat/channels/ParentChannelsComponent.vue
- frontend/src/components/chat/options/ChildOptionsPeopleComponent.vue
- frontend/src/components/chat/options/ParentOptionsComponent.vue
Functionality is working.
But we have to change the automatic refresh somehow.
> implemented new optionsPeopleComponent - no Modals for user dropdowns

- frontend/src/components/chat/peoples/ChildPeopleComponent.vue
- frontend/src/components/chat/peoples/ParentPeoplesComponent.vue
- frontend/src/views/ChatView.vue
Nice feature and simple to implement.
> implemented highlight person when in chat with

- backend/src/auth/controller/intra42.controller.ts
- frontend/src/components/leaderboard/ChildMedalComponent.vue
> 423 link must not be underlined in blue on leaderboard

- frontend/src/App.vue
- frontend/src/components/chat/chat/ParentChatComponent.vue
- frontend/src/components/chat/peoples/ParentPeoplesComponent.vue
- frontend/src/components/profile/achievement/ParentAchievementsComponent.vue
- make chat auto-scroll again
- fix eslint warning in App.vue
- fix achievements (#451)
> fix auto-scroll

- backend/docs/classes/prc_channel_channel_input.CreateChannelInput.md
- backend/docs/classes/prc_channel_channel_input.LeaveChannelInput.md
- backend/docs/classes/prc_channel_channel_input.ToggleChannelPpInput.md
- backend/src/prc/channel/channel.input.ts
> limit set to 72

- backend/docs/classes/prc_channel_channel_service.ChannelService.md
- backend/docs/classes/prc_channel_channel_user_channel_user_resolver.ChannelUserResolver.md
- backend/docs/classes/prc_channel_channel_user_channel_user_service.ChannelUserService.md
- backend/docs/classes/prc_prc_gateway.PrcGateway.md
- backend/docs/classes/users_users_service.UsersService.md
- backend/src/auth/controller/intra42.controller.spec.ts
- backend/src/auth/controller/twoFA.controller.spec.ts
- backend/src/auth/service/twoFA.service.spec.ts
- backend/src/game/game.gateway.spec.ts
- backend/src/game/game.resolver.spec.ts
- backend/src/game/game.service.spec.ts
- backend/src/prc/channel/channel-user/channel-user.resolver.spec.ts
- backend/src/prc/channel/channel-user/channel-user.resolver.ts
- backend/src/prc/channel/channel-user/channel-user.service.ts
- backend/src/prc/channel/channel.resolver.spec.ts
- backend/src/prc/channel/channel.service.spec.ts
- backend/src/prc/channel/channel.service.ts
- backend/src/prc/prc.gateway.spec.ts
- backend/src/prc/prc.gateway.ts
- backend/src/users/users.controller.spec.ts
- backend/src/users/users.resolver.spec.ts
- backend/src/users/users.service.spec.ts
- backend/src/users/users.service.ts
- frontend/src/components/chat/options/ChildOptionsPeopleComponent.vue
- frontend/src/components/chat/options/ModalUpdatePasswordComponent.vue
- frontend/src/components/chat/options/ParentOptionsComponent.vue
- frontend/src/service/ChannelUserService.ts
- frontend/src/views/ChatView.vue
- implement remove admin from channel user
- optimize find channel user function (instead of going through user database, find directly from channelUser database)
> implement remove admin from channel user
